#!/bin/bash

clear;

GREP='grep --color=always'
which egrep &>/dev/null && GREP='egrep --color=always'

shopt -s globstar

setD() {
    Dir=${1:-unknowDIR};
}

setD `git rev-parse --show-toplevel`

if [[ ! -d "$Dir/locale" ]]; then
    printf "\n\nERROR: you don't seem to be inside a LedgerSMB dir tree\n\n"
    exit
fi

if [[ -z $1 ]]; then
    read -p 'enter pattern to search for: ' pattern
else
    pattern="$@"
fi

$GREP -i -n \
    --include=*.p[lm] \
    --exclude-dir=js/ \
    --exclude-dir=js-src/ \
    --exclude-dir=*/doc/ \
    --exclude-dir=*/t/ \
    --exclude-dir=blib \
    "$pattern" $Dir/** 2>/dev/null | \
        sed "s|$Dir/||"
